# Generated by Django 5.2.6 on 2025-09-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('requiere_pago', models.BooleanField(default=False)),
                ('tarifa', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reglas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'areas_comunes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaVivienda',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('habitaciones', models.SmallIntegerField()),
                ('banos', models.SmallIntegerField()),
                ('churrasquera', models.BooleanField(default=False)),
                ('pisos', models.SmallIntegerField(default=1)),
                ('cochera', models.SmallIntegerField(default=0)),
                ('jardin', models.BooleanField(default=False)),
                ('balcon', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categorias_vivienda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('cuerpo', models.TextField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('publico', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comunicados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('ciudad', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'condominios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expensa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.TextField()),
                ('periodo', models.CharField(max_length=7)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'expensas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExpensaParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.TextField()),
                ('tarifa_por_casa', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tarifa_por_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dia_vencimiento', models.SmallIntegerField(blank=True, null=True)),
                ('multa_diaria', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'expensas_parametros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LecturaComunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lecturas_comunicado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('tipo', models.TextField()),
                ('raza', models.TextField(blank=True, null=True)),
                ('edad', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mascotas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.TextField()),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('evidencia_url', models.TextField(blank=True, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'multas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('concepto', models.TextField()),
                ('referencia_cod', models.BigIntegerField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('metodo', models.TextField()),
                ('estado', models.TextField()),
                ('qr_payload', models.TextField(blank=True, null=True)),
                ('comprobante_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parqueo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.TextField(unique=True)),
                ('ocupado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'parqueos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParqueoUsuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
                ('fecha_reserva', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parqueos_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombres', models.TextField()),
                ('apellidos', models.TextField()),
                ('num_doc', models.TextField(unique=True)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'personas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.TextField()),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('estado', models.TextField(blank=True, null=True)),
                ('qr_reserva', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reservas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResidenteVivienda',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('es_propietario', models.BooleanField(default=False)),
                ('inicio', models.DateField()),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'residente_vivienda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoInfraccion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.TextField(unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'tipos_infraccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'tipos_vehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email_login', models.TextField(unique=True)),
                ('hash_password', models.TextField()),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'usuario_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('placa', models.TextField(unique=True)),
                ('modelo', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vehiculos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entrada', models.DateTimeField()),
                ('salida', models.DateTimeField(blank=True, null=True)),
                ('medio', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'visitas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombres', models.TextField()),
                ('apellidos', models.TextField(blank=True, null=True)),
                ('num_doc', models.TextField(blank=True, null=True)),
                ('foto_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'visitantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.TextField(unique=True)),
                ('metros2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ubicacion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'viviendas',
                'managed': False,
            },
        ),
    ]
