# Generated by Django 5.2.6 on 2025-09-22 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condominio',
            options={},
        ),
    ]
