# Generated by Django 5.2.6 on 2025-09-24 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_condominio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condominio',
            options={'managed': False},
        ),
    ]
