# Generated by Django 5.2.6 on 2025-09-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_condominio_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionParqueo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'asignaciones_parqueo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('mensaje', models.TextField()),
                ('tipo', models.TextField()),
                ('prioridad', models.TextField(default='MEDIA')),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notificaciones',
                'managed': False,
            },
        ),
    ]
